Added unit test cases for below functionality:
TaskarCenterAtUW/TDEI-python-gtfs-flex-validation pull request #33
Opened 2023-06-07 14:11 UTC by sujata-m

This PR contains - 

1. Updated all unit test cases
2. Unit test cases no longer require .env file
3. Fixed test harness issue.
4. Updated test folder structure.
5. Updated Readme file

2023-06-07 20:13 UTC, sureshgaussian requested changes
There is no update to readme.md file that gives me information about how to run these new tests. I guessed the process on how to run, but was not able to run even one. Please update readme.md file on how to run the unit tests.

2023-06-08 12:32 UTC, sujata-m commented on .github/workflows/unit_test.yaml
> +          echo STORAGECONNECTION='DefaultEndpointsProtocol=https;AccountName=tdeisamplestorage;AccountKey=l9JSJCGq9NrXqRVKApSk1wwV27aWaOVuxeY0NWOZz2svIlJzyncr3UFTzLoAanFbmJIeb2WmwIcS+AStj5gELg==;Endp
@MashB told to remove this pipeline, removing the pipeline

2023-06-08 13:43 UTC, susrisha requested changes
one minor change in README

2023-06-08 13:43 UTC, susrisha commented on README.md
> +1. Set up the python env locally, see [here](#how-to-setup-aand-build)
typo I think. it should be `how-to-setup-and-build` (There are two `a` in the above

2023-06-20 06:24 UTC, sureshgaussian approved these changes
I am approving this PR. I ran the tests and looked at the report. It is fine. However, we need some changes, which we can pick up as a clean up task. I will file a devboard item for the improvements. https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/358/

2023-06-20 14:12 UTC, merged