Multi thread issue fix
TaskarCenterAtUW/TDEI-python-gtfs-flex-validation pull request #62
Opened 2024-08-20 13:07 UTC by susrisha

- Fixes the issue with multi threaded approach
- There is an inherent issue in the Library where the files are extracted to the same folder everytime. 
- This is fixed by using 1 concurrent message at a time and processing it
- Also removed creation of a separate thread each time. The messages are received in a threadpool execution manner and need not be handled by a separate thread each time.
### Testing
- This is tested with a sample topic and a sample message is run 10 times and 15 times in two consecutive sessions. Both times, it was able to execute and respond with all the required parameters and details.

2024-08-20 13:12 UTC, susrisha commented on src/gtfx_flex_validator.py
> +        self.request_topic = self.core.get_topic(topic_name=self.settings.request_topic_name,max_concurrent_messages=1)
make it env configurable. if not available, pick as 1.

2024-08-20 13:16 UTC, susrisha commented on src/gtfx_flex_validator.py
> +                self.process_message(upload_msg)
put a try catch here

2024-08-21 05:18 UTC, MashB commented on src/config.py
> +    max_concurrent_messages: int = os.environ.get('MAX_CONCURRENT_MESSAGES', 1)
can you please update the readme for MAX_CONCURRENT_MESSAGES variable

2024-08-21 05:21 UTC, MashB requested changes

2024-08-21 05:21 UTC, MashB commented on src/gtfx_flex_validator.py
> +                self.process_message(upload_msg)
Can we add try catch block to process_message method. In case failure we need to respond to queue about failure

2024-08-21 05:28 UTC, MashB approved these changes

2024-08-21 05:29 UTC, merged